language: php
php:
  - 5.3
  - 5.4

services:
  - memcached


before_script:
 - phpenv config-add tests/memcache.ini
 - git clone -q https://github.com/phalcon/cphalcon.git && git checkout 1.2.3
 - (cd cphalcon/build/32bits; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks"; phpize && ./configure --enable-phalcon && make -j2 && sudo make install && phpenv config-add ../../../tests/phalcon.ini)
 - wget http://getcomposer.org/composer.phar
 - php composer.phar install

script: (cd tests; phpunit --debug)
