language: php
php:
  - 5.3
  - 5.4

services:
  - memcached


before_script:
 - phpenv config-add tests/memcache.ini
 - git clone -q https://github.com/phalcon/cphalcon.git
 - git fetch origin && git checkout -b origin/1.2.3
 - (cd cphalcon/build; ./install && phpenv config-add ../../tests/phalcon.ini)
 - wget http://getcomposer.org/composer.phar
 - php composer.phar install

script: (cd tests; phpunit --debug)
